model:
  model_name: "base.en"
  model_dir: "/home/ar-in-u-301/Documents/codes/techbuddy/src/backend/models"

questions:
  file_path: "/home/ar-in-u-301/Documents/codes/techbuddy/data/questions/question_bank.json"

logs:
  log_dir: "/home/ar-in-u-301/Documents/codes/techbuddy/logs"
  log_level: "INFO"