stt_model:
  model_name: "base.en"
  model_dir: "/app/src/backend/models"

questions:
  file_path: "/app/data/questions/question_bank.json"

logs:
  log_dir: "/var/log/techbuddy"
  log_level: "INFO"

openai:
  stt_cleaner_model: "gpt-4o-mini-2024-07-18"

threading:
  max_workers: 20

minio:
  bucket_name: "techbuddy"